version: '3'


### MARIADB ###

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb:/var/lib/mysql  # Mount a volume to persist database data
    expose:
      - "3306"
    networks:
      - inception
    restart: unless-stopped  # Always restart the container unless it is explicitly stopped
    env_file: .env  # Load environment variables from the '.env' file
    healthcheck:
      test: mysqladmin ping --host=localhost -p${SQL_ROOT_PASSWORD}  # Health check command to verify the service is up
      interval: 5s  # Time between health checks
      timeout: 1s  # Health check timeout
      retries: 20  # Number of retries before marking the service as unhealthy
      start_period: 5s  # Start period before starting health checks



### WORDPRESS ###

  wordpress:
    image: wordpress
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/html  # Mount a volume to persist WordPress data
    expose:
      - "9000"
    networks:
      - inception
    restart: unless-stopped  # Always restart the container unless it is explicitly stopped
    env_file: .env  # Load environment variables from the '.env' file
    depends_on:
      mariadb:
        condition: service_healthy  # Wait for the MariaDB service to be healthy before starting



### NGINX ###

  nginx:
    image: nginx
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/html  # Mount a volume to serve wp files
    depends_on:
      - wordpress  # Wait for the wp service to be ready before starting
    ports:
      - "443:443"  # Map port 443 on the host to port 443 on the container
    networks:
      - inception
    restart: unless-stopped  # Always restart the container unless it is explicitly stopped
    env_file: .env  # Load environment variables from the '.env' file


### VOLUMES ###

volumes:
  mariadb:
    driver: local  # Use the local driver for the volume
    driver_opts:
      type: 'none'  # No specific type, bind to a host directory
      o: 'bind'  # Bind the volume to a host directory
      device: '/home/jrouillo/data/mariadb'  # Path to the host directory for MariadbB data
  wordpress:
    driver: local  # Use the local driver for the volume
    driver_opts:
      type: 'none'  # No specific type, bind to a host directory
      o: 'bind'  # Bind the volume to a host directory
      device: '/home/jrouillo/data/wordpress'  # Path to the host directory for wp data

networks:
  inception:
    name: inception
